### PR TITLE
Added some scripted triggers to artifact loss

### PR DESCRIPTION
**Pull request by Ramit110**
I was going to do more and such, this is just to simplify files and the like, if you don't mind I'll add more of this kind of thing.

### CODE REVIEW

**Comment by Ramit110** [comment]
I look at this and I see now that the whole ```			NOT = {	
				viet_artifact_loss_three_flags = yes
			}``` can just be ``viet_artifact_loss_three_flags = no``

**Comment by Ramit110** [comment]
@cybrxkhan Am I good to do more of this kind of thing?

**Comment by cybrxkhan** [comment]
Oops forgot to comment earlier! Thanks for helping me with this, it'll go in the update I'm planning to release today. If you notice any in the future it definitely wouldn't hurt to help optimize things.

**Comment by Ramit110** [comment]
I will, expect many more in the coming weeks.

**Comment by cybrxkhan** [comment]
Sounds good! Much appreciated.

**Pull request merged**
