### PR TITLE
Missing OCC localisation

### PR DESCRIPTION
**Pull request by IhateTrains**
- Some localisation I wrote for WtWSMS, was missing in VIET
- Event calling Validation

If you want, I can update the French OCC localisation from WtWSMS.

### CODE REVIEW

**Comment by cybrxkhan** [comment]
Thanks! I really appreciate it.

**Comment by cybrxkhan** [comment]
And yes, since I don't know any French please feel free to add any French localisation you guys want or have.

**Comment by IhateTrains** [comment]
OK, I will add at least some of the French localisation of VIET lines. Loup is probably the one to be credited for it.

**Comment by cybrxkhan** [comment]
No problem, and thanks again - also as a heads up I'll' probably be punting out the first release of the mod later today.

**Comment by IhateTrains** [comment]
Sounds like a good Christmas gift :)

**Comment by NicolasGrosjean** [comment]
For the credits of the French translation, Domper59 should be added. I have convinced him to translate WtWSMS with Loup and me but he didn't use GitHub at the beginning, so Loup uploaded a great part of his work (like [this commit](https://github.com/loup99/WtWSMS/commit/62dd945c893d1041bca2e83e1bfd782464103430#diff-691df944a07f58dc28e65bd27dd36c7d)).

He has been the main contributor of the French translation on the VIET files.

**Comment by IhateTrains** [comment]
That's right, I forgot about the other translators. Sorry.

**Comment by cybrxkhan** [comment]
Alright, no problem, I'll add Domper59 and you to credits as well! You guys did a pretty good job covering all the old VIET stuff.

**Pull request merged**
